packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  '@nestjs/core': true
  '@prisma/client': true
  '@prisma/engines': true
  prisma: true
  sharp: true

# Пакеты, которым разрешено выполнять postinstall-сборку (pnpm 10+).
onlyBuiltDependencies:
  - "@nestjs/core"
  - "@prisma/client"
  - "@prisma/engines"
  - prisma
  - sharp
